const seed = {
  tasks:[
    {id:1,title:'Finish client growth proposal',workspace:'Northstar',project:'Q4 Growth Plan',time:'9:00 AM',duration:45,priority:'High',status:'Planned',done:false},
    {id:2,title:'Review hiring scorecard',workspace:'Northstar',project:'People',time:'1:30 PM',duration:30,priority:'Medium',status:'Planned',done:false},
    {id:3,title:'Call Mom about weekend plans',workspace:'Personal',project:'Family',time:'5:30 PM',duration:15,priority:'Medium',status:'Planned',done:false},
    {id:4,title:'Send Q3 dashboard to Maya',workspace:'Northstar',project:'Operations',time:'',duration:20,priority:'High',status:'Waiting',done:false},
    {id:5,title:'Book dentist appointment',workspace:'Personal',project:'Life admin',time:'',duration:10,priority:'Low',status:'Inbox',done:false}
  ],
  journal:[{date:'Sep 18',text:'I keep losing the afternoon to requests that do not move the larger work forward. The proposal needs a protected block tomorrow.'}],
  nextId:6
};
let state = JSON.parse(localStorage.getItem('executive-os-v1')||'null') || seed;
let active='today', timer=null, seconds=45*60, running=false, captureType='Task';
const save=()=>localStorage.setItem('executive-os-v1',JSON.stringify(state));
const $=s=>document.querySelector(s);
const icon={today:'◉',journal:'✦',brain:'◌',plan:'▦',tasks:'✓',projects:'◇',goals:'↗',focus:'◐',review:'◒',waiting:'↳',decisions:'◆'};
function nav(){return `<aside class="sidebar"><div class="brand"><span class="mark">E</span> EXECUTIVE OS</div>
  <div class="nav-section"><div class="nav-label">THINK</div>${navItem('journal','Journal')}${navItem('brain','Brain dump')}</div>
  <div class="nav-section"><div class="nav-label">PLAN</div>${navItem('today','Today')}${navItem('tasks','Tasks')}${navItem('projects','Projects')}${navItem('goals','Goals')}</div>
  <div class="nav-section"><div class="nav-label">DO</div>${navItem('focus','Focus')}${navItem('waiting','Waiting on')}</div>
  <div class="nav-section"><div class="nav-label">REVIEW</div>${navItem('review','Weekly review')}${navItem('decisions','Decisions')}</div>
  <div class="workspace"><div class="avatar">ZC</div><div>Zaira Collazo<small>Everything</small></div></div></aside>`}
function navItem(id,label){return `<button class="nav-item ${active===id?'active':''}" data-nav="${id}"><span class="ico">${icon[id]}</span><span>${label}</span></button>`}
function topbar(){return `<div class="topbar"><div class="date-label">FRIDAY, SEPTEMBER 18 · WEEK 38</div><button class="quick" id="quick"><b>+</b> QUICK ADD <span style="opacity:.55;font-size:10px">⌘K</span></button></div>`}
function today(){let top=state.tasks.filter(x=>!x.done).slice(0,3);let completed=state.tasks.filter(x=>x.done).length;return `<main class="main">${topbar()}<section class="headline"><div><h1>Good morning, Zaira.</h1><p>Make room for the work only you can do.</p></div><div class="clock"><b id="live-clock">9:42</b><span>FRIDAY MORNING</span></div></section>
<div class="top-grid"><section class="card priorities"><div class="card-head"><div class="eyebrow">Today’s top 3</div><button class="text-link" data-nav="tasks">View all</button></div>${top.map((t,i)=>priority(t,i)).join('')}</section>
<section class="card capacity"><div class="card-head"><div class="eyebrow">Capacity</div><span class="tag high">5H OVER</span></div><div class="capacity-copy">Your calendar is <b>overcommitted</b> by 5 hours.</div><div class="meter"><i></i></div><div class="capacity-row"><span>Available work time</span><b>12 HRS</b></div><div class="capacity-row"><span>Planned work</span><b>17 HRS</b></div><button class="text-link" style="margin:8px 19px" data-nav="tasks">Rebalance plan →</button></section></div>
<section class="card timeline-card"><div class="card-head"><div><div class="eyebrow">Daily timeline</div><b style="font-size:14px;display:block;margin-top:4px">Friday, September 18</b></div><button class="text-link" id="add-block">+ Time block</button></div><div class="timeline"><div class="time-labels"><span>9 AM</span><span>10 AM</span><span>11 AM</span><span>12 PM</span><span>1 PM</span></div><div class="time-lane"><div class="block focusblock" draggable="true" data-block="proposal"><b>Finish client growth proposal</b><span>9:00–9:45 · Focus</span><span class="handle">↕</span></div><div class="block meeting" draggable="true" data-block="leadership"><b>Leadership sync</b><span>10:30–11:15 · Northstar</span><span class="handle">↕</span></div><div class="block personal" draggable="true" data-block="lunch"><b>Lunch + reset</b><span>12:15–12:45 · Personal</span></div></div></div></section>
<div class="bottom-grid"><section class="card next-card"><div class="eyebrow">What should I be doing?</div><div class="next-title">Finish client growth proposal</div><div class="next-meta">45 minutes · High impact · Due today · Focus time available</div><button class="start" id="start-focus">START FOCUS →</button></section><section class="card insights"><div class="card-head"><div class="eyebrow">Executive observations</div><button class="text-link" data-nav="review">Review</button></div><div class="insight"><i class="bullet"></i><p><strong>Strategic work</strong> has been moved three times this week.</p></div><div class="insight"><i class="bullet" style="background:#8fc5d5"></i><p>You have <strong>3 items waiting</strong> on someone else.</p></div><div class="insight"><i class="bullet" style="background:#e5ae77"></i><p>Your focus sessions are strongest <strong>before noon.</strong></p></div></section></div></main>`}
function priority(t,i){return `<div class="priority"><button class="check ${t.done?'done':''}" data-check="${t.id}">${t.done?'✓':''}</button><div><div class="task-title">${t.title}</div><div class="task-meta">${t.workspace} · ${t.project} · ${t.duration} min</div></div><span class="tag ${i===0?'high':''}">${t.priority}</span></div>`}
function journal(brain=false){let title=brain?'Brain dump':'Journal'; let sub=brain?'Write it exactly as it arrives. We’ll create structure when you’re ready.':'No prompts, no categories. Just get it out of your head.';return `<main class="main journal-page">${topbar()}<h1 class="page-title">${title}</h1><p class="page-sub">${sub}</p><section class="card journal-editor"><textarea id="journal-text" placeholder="What’s on your mind?">${brain?'':''}</textarea><div class="editor-foot"><select class="select"><option>Personal & professional</option><option>Northstar</option><option>Personal</option></select><button class="primary" id="process">${brain?'PROCESS MY BRAIN DUMP':'PROCESS THIS'} →</button></div></section><div id="extraction-root"></div></main>`}
function tasks(){return `<main class="main list-page">${topbar()}<h1 class="page-title">Tasks</h1><p class="page-sub">A clear list, not a graveyard.</p><div class="filterbar"><button class="filter active">Everything</button><button class="filter">Today</button><button class="filter">Northstar</button><button class="filter">Personal</button><button class="filter">Waiting</button></div><section class="card task-table">${state.tasks.map(t=>`<div class="task-row"><button class="check ${t.done?'done':''}" data-check="${t.id}">${t.done?'✓':''}</button><div><b>${t.title}</b><small style="display:block;margin-top:3px">${t.project} · ${t.duration} min</small></div><span>${t.workspace}</span><span class="tag ${t.priority==='High'?'high':''}">${t.priority}</span><span class="tag">${t.status}</span><button class="text-link" data-focus-task="${t.id}">◐</button></div>`).join('')}</section></main>`}
function focus(){let t=state.tasks.find(x=>!x.done)||state.tasks[0];return `<main class="main"><div class="focus-screen"><div class="eyebrow">FOCUS SESSION · NORTHSTAR</div><div class="focus-task">${t.title}</div><p class="page-sub" style="margin-top:12px">One thing. Enough time. No noise.</p><div class="timer" id="timer">${format(seconds)}</div><div class="timer-buttons"><button class="pause" id="timer-toggle">${running?'PAUSE':'START'} TIMER</button><button class="end" id="complete-focus">COMPLETE TASK</button><button class="end" data-nav="today">EXIT</button></div><div style="margin-top:37px;color:var(--muted);font-size:12px">Quick note <span style="display:inline-block;border-bottom:1px solid #bfc7c0;min-width:220px;text-align:left;margin-left:10px">&nbsp;</span></div></div></main>`}
function review(){let done=state.tasks.filter(t=>t.done).length;return `<main class="main review-page">${topbar()}<h1 class="page-title">Weekly executive review</h1><p class="page-sub">See what moved, what needs a decision, and what can wait.</p><div class="top-grid"><section class="card" style="padding-bottom:18px"><div class="card-head"><div class="eyebrow">Week at a glance</div></div><div style="display:grid;grid-template-columns:repeat(3,1fr);padding:3px 19px;gap:8px"><div><b style="font-family:'Playfair Display';font-size:32px">${done+8}</b><small style="display:block;color:var(--muted)">completed</small></div><div><b style="font-family:'Playfair Display';font-size:32px">4</b><small style="display:block;color:var(--muted)">delegated</small></div><div><b style="font-family:'Playfair Display';font-size:32px">3</b><small style="display:block;color:var(--muted)">waiting</small></div></div></section><section class="card"><div class="card-head"><div class="eyebrow">Time allocation</div></div><div class="capacity-row"><span>Focus</span><b>9H 20M</b></div><div class="capacity-row"><span>Meetings</span><b>11H 15M</b></div><div class="capacity-row"><span>Admin</span><b>4H 10M</b></div></section></div><section class="card" style="padding:20px"><div class="eyebrow">Recurring theme</div><h2 style="font-family:'Playfair Display';font-size:29px;letter-spacing:-.04em;margin:10px 0 4px">Protecting focus</h2><p class="page-sub" style="margin:0">You mentioned unplanned requests in 3 journal entries. Related to 2 tasks and 1 decision.</p><button class="primary" style="margin-top:16px">EXPLORE THEME →</button></section></main>`}
function simple(name,sub){return `<main class="main list-page">${topbar()}<h1 class="page-title">${name}</h1><p class="page-sub">${sub}</p><section class="card" style="padding:25px;text-align:center;color:var(--muted)">Your ${name.toLowerCase()} space is ready for the next decision.</section></main>`}
function render(){let page=active==='today'?today():active==='journal'?journal():active==='brain'?journal(true):active==='tasks'?tasks():active==='focus'?focus():active==='review'?review():active==='waiting'?simple('Waiting on','Work that belongs to others, still visible to you.'):active==='decisions'?simple('Decisions','Thought → decision → action.'):simple(active[0].toUpperCase()+active.slice(1),'Your executive system, organized around what matters.');$('#app').innerHTML=`<div class="shell">${nav()}${page}</div>`;bind()}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{active=b.dataset.nav;running=false;clearInterval(timer);render()});document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{let t=state.tasks.find(x=>x.id==b.dataset.check);t.done=!t.done;save();render()});$('#quick')?.addEventListener('click',openCapture);$('#add-block')?.addEventListener('click',openCapture);$('#start-focus')?.addEventListener('click',()=>{active='focus';render()});document.querySelectorAll('[data-focus-task]').forEach(b=>b.onclick=()=>{active='focus';render()});document.querySelectorAll('[data-block]').forEach(b=>{b.ondragstart=e=>e.dataTransfer.setData('block',b.dataset.block);b.onclick=()=>b.classList.toggle('expanded')});document.querySelector('.time-lane')?.addEventListener('dragover',e=>e.preventDefault());document.querySelector('.time-lane')?.addEventListener('drop',e=>{e.preventDefault();let b=document.querySelector(`[data-block="${e.dataTransfer.getData('block')}"]`);if(b){let y=Math.max(0,Math.min(165,e.offsetY-20));b.style.top=y+'px';b.querySelector('span').textContent='Rescheduled · drag to adjust'}});$('#process')?.addEventListener('click',processJournal);$('#timer-toggle')?.addEventListener('click',toggleTimer);$('#complete-focus')?.addEventListener('click',()=>{let t=state.tasks.find(x=>!x.done);if(t)t.done=true;save();active='today';running=false;clearInterval(timer);render()});window.onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCapture()}};clock()}
function clock(){let el=$('#live-clock');if(el)el.textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function processJournal(){let text=$('#journal-text').value.trim();if(!text)return;state.journal.unshift({date:'Today',text});save();$('#extraction-root').innerHTML=`<section class="card extraction"><div class="card-head"><div><div class="eyebrow">Possible operational items</div><b style="display:block;margin-top:4px">You decide what becomes real.</b></div></div><div style="padding:0 19px"><h3>POSSIBLE TASKS</h3><div class="extracted"><input checked type="checkbox"><span>Protect a focus block for the client proposal</span><button class="dismiss">Dismiss</button></div><div class="extracted"><input checked type="checkbox"><span>Review requests competing for afternoon time</span><button class="dismiss">Dismiss</button></div><h3>POSSIBLE DECISION</h3><div class="extracted"><input type="checkbox"><span>Set a boundary for unplanned afternoon requests</span><button class="dismiss">Dismiss</button></div><div style="padding:15px 0"><button class="primary" id="accept-items">ADD SELECTED ITEMS</button></div></div></section>`;$('#accept-items').onclick=()=>{state.tasks.push({id:state.nextId++,title:'Protect a focus block for the client proposal',workspace:'Northstar',project:'Q4 Growth Plan',duration:45,priority:'High',status:'Planned',done:false});save();active='tasks';render()}}
function openCapture(){captureType='Task';$('#modal-root').innerHTML=`<div class="modal-back" id="back"><section class="modal"><h2>Capture</h2><p>Drop it here first. You can add structure later.</p><div class="capture-types">${['Task','Journal','Reminder','Meeting','Idea','Decision'].map(x=>`<button class="capture-type ${x==='Task'?'selected':''}" data-type="${x}">${x}</button>`).join('')}</div><input id="capture-title" placeholder="What needs your attention?" autofocus><textarea id="capture-note" placeholder="Add context, if useful"></textarea><div class="modal-footer"><button class="cancel" id="cancel">Cancel</button><button class="primary" id="save-capture">CAPTURE →</button></div></section></div>`;document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{captureType=b.dataset.type;document.querySelectorAll('[data-type]').forEach(x=>x.classList.toggle('selected',x===b))});$('#cancel').onclick=closeModal;$('#back').onclick=e=>{if(e.target.id==='back')closeModal};$('#save-capture').onclick=()=>{let title=$('#capture-title').value.trim();if(!title)return;if(captureType==='Journal'){state.journal.unshift({date:'Today',text:title+' '+$('#capture-note').value})}else{state.tasks.unshift({id:state.nextId++,title,workspace:'Everything',project:captureType,duration:25,priority:'Medium',status:'Inbox',done:false})}save();closeModal();active=captureType==='Journal'?'journal':'tasks';render()}}
function closeModal(){$('#modal-root').innerHTML=''}
function format(s){let m=Math.floor(s/60),r=s%60;return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`}
function toggleTimer(){running=!running;if(running){timer=setInterval(()=>{if(seconds>0){seconds--;let e=$('#timer');if(e)e.textContent=format(seconds)}else{running=false;clearInterval(timer)}},1000)}else clearInterval(timer);let b=$('#timer-toggle');if(b)b.textContent=running?'PAUSE':'START';}
render();
